[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "paperless-ocr"
version = "1.0.0"
dependencies = [
    "requests==2.32.3",
    "openai==1.35.10",
    "Pillow==10.4.0",
    "pdf2image==1.17.0",
    "structlog==24.2.0",
]

[tool.setuptools.packages.find]
where = ["src"]